---
title: 'Choose context'
teaching: 10
exercises: 2
---

## Step 1: Choose context and type of application (10 min)

In this step you can choose the context and type of the digital experience application to evaluate. This can be:

= selected from the application examples in the list below
= an application that you have been planning/designing through other training sessions (e.g. [Digital Exhibition Design tutorial](https://universityofbrighton.github.io/2023-exhibition-design/index.html))
- an application of your choice.

You can find a [list of examples applications](https://universityofbrighton.github.io/2023-exhibition-design/more-information.html#interactive-multimedia-experiences-in-ch).


When you choose your application, use the 5W1H method, which is helpful to gather essential information about it:

-	**Who**: who is the user of the application (audiences)?
-	**What**: what will the user/s do? what is their task/s?
-	**Where**: where will the user/s live the experience (physical environment, conditions, other users around)?
-	**When**: when will the user/s perform the task (at home, in the exhibition?)
-	**Why**: why do users perform the tasks (purpose, goal)?
-	**How**: how will they perform the tasks?


