---
title: 'Data Analysis'
teaching: 10
exercises: 2
---

## Data analysis and reporting 

Data analysis depends on different factors, including type and volume of data, available time to analyse, cost, access to software, staff with skills to do the analysis and ultimately the purpose of the analysis itself.

Once you decide on an approach, reading through the data helps to identify emerging patterns, problematic questions, or unexpected results. Collaboration when going through the data can enhance insights and stimulate new ideas. When analysing data, quantitative and qualitative information will have to be interpreted in meaningful ways to address the main purpose of the evaluation. Depending on the data collected and analysis skills, providing quantitative information which is accompanied by qualitative insights can result in a more robust, well-rounded evaluation report.

Data of quantitative nature will usually be analysed by using appropriate software (Excel, SPSS, R and more). Deploying survey platforms (e.g., [LimeSurvey](https://www.limesurvey.org/), [SurveyMonkey](https://www.surveymonkey.co.uk/welcome) and [Google Forms](https://www.google.com/forms/about/)), as mentioned before, facilitates data analysis and visualisation. Identifying data parameters and relations helps to analyse data. For instance, it is possible to relate the age of participants with performance when interacting with a digital application. Percentages are used in analysis for larger sets of data, whereas when the sample is small, stating the number of participants should be enough for the analysis.

Qualitative data on the other hand, can be more difficult to analyse. Software is also available for qualitative data analysis (e.g., NVivo, ATLAS.ti). When analysing qualitative information, it is good to have an open approach towards the data and go through the dataset various times before starting to code responses and highlight key themes, as they emerge from discussions, agreements and disagreements. Both positive and negative aspects should be noted, analysed and presented to avoid bias and ensure that an honest representation of the evaluation will be provided. Identifying noteworthy words, phrases, and unexpected discoveries can enhance the depth of the analysis report. Incorporating relevant quotes can further elucidate essential aspects of qualitative insights within the report.

Now with regards to the evaluation report, some general principles to follow when producing this document include:

- Articulating clear statements regarding the achievement of success criteria.
- Ensure anonymity of participants in the report.
- Utilising visual aids and percentages for better comprehension, incorporating charts, graphs, and word clouds.
- Enhancing understanding by including images that visually represent results, ensuring proper consent from individuals depicted.
- Integrating anonymised quotes from qualitative data.
- Providing context by including comparisons with previous years' data and similar museums, events, or projects.

Lastly, the report must be clearly structured to address all the evaluation aspects and demonstrate the rationale, methodology, realisation and interpretation of the results along with future plans. Hence, the report should comprise:

- Executive summary, highlighting the key points of the report.
- Introduction and background, providing the context of the digital experience project in terms of aim/s, objectives, outputs and outcomes.
- Methodology, explaining data collection methods' choices, sampling, pilots, lessons learned, changes.
- Discussion, presenting evidence from the data, analysing key themes and reflecting on strengths, and weaknesses of the digital experience and its contribution towards the desired outcomes.
- Conclusion, summarising the findings of the evaluation.
- Recommendations and future plans, explaining how the evaluation will enable changes in policies, strategic thinking and actions towards the desired outcomes.
- Appendices with copies of the survey, interview questions, observation protocols etc.

More information on data analysis and reporting:

- Share Museums East (2020). Evaluation Toolkit for Museums. Retrieved from: [https://www.sharemuseumseast.org.uk/wp-content/uploads/2020/05/SHARE_Evaluation_Toolkit_FINAL_WEB.pdf](https://www.sharemuseumseast.org.uk/wp-content/uploads/2020/05/SHARE_Evaluation_Toolkit_FINAL_WEB.pdf)
- British Museum (2006-). Visitor Research and Evaluation. Retrieved from: [https://www.britishmuseum.org/research/projects/visitor-research-and-evaluation](https://www.britishmuseum.org/research/projects/visitor-research-and-evaluation)
- South West Museum Development. Effective Evaluation Planning. Retrieved from: [https://southwestmuseums.org.uk/resources/effective-evaluation-planning/](https://southwestmuseums.org.uk/resources/effective-evaluation-planning/)
- The Audience Agency. Visitor Guidelines: Part 3. How to Analyse Visitor Survey Responses. Retrieved from: [https://www.culturehive.co.uk/wp-content/uploads/2020/10/AA_How-to-Analyse-Survey-Responses-1.pdf](https://www.culturehive.co.uk/wp-content/uploads/2020/10/AA_How-to-Analyse-Survey-Responses-1.pdf)






