---
title: 'Define the essentials'
teaching: 10
exercises: 2
---

## Step 3: Define the essentials of evaluation plan through a checklist 

In this step, you will deploy a checklist as introduced by the Share Museums East (2020). Evaluation Toolkit for Museums. Page 32. Retrieved from: [https://www.sharemuseumseast.org.uk/wp-content/uploads/2020/05/SHARE_Evaluation_Toolkit_FINAL_WEB.pdf](https://www.sharemuseumseast.org.uk/wp-content/uploads/2020/05/SHARE_Evaluation_Toolkit_FINAL_WEB.pdf) 

You can find the questions of the checklist below:

### Rationale and context for evaluation

- What is the project / activity you are evaluating? Why are you carrying out the evaluation - what is its purpose?
- What type of evaluation is it (front-end, formative and/or summative)? If your evaluation will cover more than one of these, how will your stages of evaluation link to one another?
- Why will the findings be of interest and who will they be of interest to?
- Set your baselines – establish what quantitative and qualitative information you have currently that relates to your project.
- Decide how you will plan your evaluation and measure any outcome / impacts.

### Aims, objectives, outcomes, impacts, outputs	

- What are the aims and objectives of this activity / project?
- What are the proposed outputs of this activity / project?
- What are the proposed outcomes and impacts of this activity / project?

### In-house or sourced evaluation	

- Do you have the staff and time to deliver the evaluation in-house?
- If you need to commission an external consultant to do the evaluation for you, you will need to have answered most, if not all, the questions in the two boxes above if you are to write an evaluation brief. Thinking about answers to questions in the three boxes below will also help you to gauge whether the responses to your brief are realistic and appropriate to your needs.
- What needs to go in an evaluation brief for an external consultant?


### Methods	

- What are the proposed evaluation methods and how will these capture information that can measure your aims, objectives, outputs and outcomes?
- What baseline information do you have or need in order to demonstrate the progression or ‘distance travelled’ by your project or activity? If you don’t have this already, how could you collect it at the start of the activity?

### Participants	

- Who are your intended participants / target groups and how many people do you need to recruit or involve?
- What are your proposed sampling methods?
- Are your methods accessible to your intended audience?
- Do you need to consider any ethical issues? (e.g. are you working with vulnerable groups, do you need informed consent?)
- How will you collect feedback from people delivering the service to your visitors?


### Recording data	

- What methods do you propose to use to record the data gathered?
- Will these allow you to interrogate the data easily?
- Will the storage of data comply with [GDPR](https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/) and the [Data Protection Act 2018](https://www.gov.uk/data-protection)?

This checklist and questions originate from:

Share Museums East (2020). Evaluation Toolkit for Museums. Page 32. Retrieved from: [https://www.sharemuseumseast.org.uk/wp-content/uploads/2020/05/SHARE_Evaluation_Toolkit_FINAL_WEB.pdf](https://www.sharemuseumseast.org.uk/wp-content/uploads/2020/05/SHARE_Evaluation_Toolkit_FINAL_WEB.pdf)


