---
title: 'Think of the user'
teaching: 10
exercises: 2
---

## Step 2: Think of the user of this application (or use already developed user persona) (10 min)

In this step you will think of the user of this application (i.e., application that you have planned in previous sessions, and you aim to evaluate or application chosen from the list in step 1).

If you have already developed a persona through the persona building method in the [Digital Exhibition Design tutorial](https://universityofbrighton.github.io/2023-exhibition-design/choose-user.html#step-2-choose-your-user-through-the-persona-building-method-15-min), please use the already existing persona/s.

This step aims to help you think about your user/s and their needs as a preparation stage for defining the essentials of your evaluation. It can also be particularly useful to identify the participants of your evaluation study.

Now think of how your persona/s would experience the digital application. To do that, look at various aspects of the UX (user experience) and try to think of how the application addresses questions, such as the following:

- How good is the provided information and media for the user/s?
- How easy is it for the user/s to interact with the application?
- Does the application provide what the user/s need?
- How quickly can the user/s find what they are looking for?
- Do the visual elements/aesthetics of the application please the user/s?


